### ISSUE TITLE
The examples files are still hosted in the example repository

### ISSUE THREAD

**Issue by Bachibouzouk** [OpenEnergyPlatform/metadata#10]
https://github.com/OpenEnergyPlatform/examples/tree/develop/metadata

One should place a readme file with a redirection and host the relevant files here

**Comment by 4lm** [comment]
Yes, I agree! As discussed with @Ludee, will do!

**Comment by Ludee** [comment]
Seems like an open task.
This issue is somehow related to #26.

**Comment by jh-RLI** [comment]
@Ludee okay!

**Comment by jh-RLI** [comment]
@Ludee i think this is no longer necessary as the examples repo will be restructured and the metadata template and example files are already here.

**Comment by jh-RLI** [comment]
I will close this, reopen if necessary!
