### ISSUE TITLE
UnicodeDecodeError on Windows for schema v140

### ISSUE THREAD

**Issue by 4lm** [OpenEnergyPlatform/metadata#17]
```
E       UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 31972: character maps to <undefined>

C:\[...]\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py:23: UnicodeDecodeError
```
I work at home on a Windows machine (Linux at RLI). I get above error in my tests for every test that tries to import schema v140 in branch . On Linux its running perfect on branch "feature/add-required-properties", succeeded travis tests in #11 proof that. I will look into it!

**Comment by 4lm** [comment]
Reading the file as binary files ("rb" instead of "r") solves it. Will do PR.

**Comment by wingechr** [comment]
alternatively, specify the correct encoding in the `open` function, e.g. `with open('...', 'r', encoding='utf-8')`

**Comment by Ludee** [comment]
I think the suggestion to use explicit encoding is better.
