### ISSUE TITLE
Need some help for finalizing schema implementation!

### ISSUE THREAD

**Issue by 4lm** [OpenEnergyPlatform/metadata#4]
Hi all,

as [announced](https://github.com/OpenEnergyPlatform/organisation/issues/26#issuecomment-548330375) today, I created a new [metadata repo](https://github.com/OpenEnergyPlatform/metadata) with schemas, examples, templates and (validation) tests for v130 and v140. I also implemented the descriptions into the schemas of v130 and v140. I know there is still stuff to do #1, #2, #3 until this is a complete, pip installable package.

But for now, I need your feedback on a more conceptual, metadata schema side:

- I need decisions on all elements which have "TBD" in it.
- I need a decision if null data type is allowed instead of string type in v140. Personally, I find it a good idea.

Here are the links to v130 and v140 of the metadata schemas:

- v130: https://github.com/OpenEnergyPlatform/metadata/blob/develop/metadata/v130/schema.json
- v140: https://github.com/OpenEnergyPlatform/metadata/blob/develop/metadata/v140/schema.json
 
Note: I'm not in the office until next Thursday (7th Nov.) so this request is not super urgent!

Thanks in advance!

**Comment by 4lm** [comment]
Hi all,

first phase is done! The metadata package is now installable as pip package and the the repo makes use of CI via travis/tox.

Next steps are implementing oep-metadata into omi, cleaning up the examples repo ...

... and I still need the TBD review on the metadata json schemas (maybe @christian-rli can help me with this?):

- v130: https://github.com/OpenEnergyPlatform/metadata/blob/develop/metadata/v130/schema.json
- v140: https://github.com/OpenEnergyPlatform/metadata/blob/develop/metadata/v140/schema.json

**Comment by 4lm** [comment]
> ... and I still need the TBD review on the metadata json schemas (maybe @christian-rli can help me with this?):

Issue #9 also touches this topic!

**Comment by 4lm** [comment]
Hi @christian-rli,

I cleared all TBDs in schema v1.4.0: https://github.com/OpenEnergyPlatform/metadata/commit/dc9a0be001e3d83fce16c26b13ff13daf5c6f3cc

Can you have a look, if this still complies with your original intend? Thanks!

PS: In a next commit I will add constrains ("required", enums etc.). So, stay tuned :guitar:

**Comment by 4lm** [comment]
@christian-rli, please note: in issue #9 im discussing with @Bachibouzouk the use of mandatory properties via "required" schema attribute.

**Comment by 4lm** [comment]
I also would like to use enumerations for items in arrays and property values, which follow a certain standard (e. g.: IETF (BCP47), SPDX etc.) and because of this also have a finite amount of values which qualifies it for using enumeration. This also could be super helpful for the data entry, because then we can generate drop down menus or lists with pre-filled with values the use can choose from.

What do you think!

**Comment by 4lm** [comment]
> I also would like to use enumerations for items in arrays and property values, which follow a certain standard (e. g.: IETF (BCP47), SPDX etc.) 

Mhh :thinking:, this are way too many values! For example IETF has  around 760 values (which also could change over time)? SPDX is also quite a lot of values. I would say, it makes more sense to declare this out of scope and if so let [oep](https://github.com/OpenEnergyPlatform/oeplatform) or [omi](https://github.com/OpenEnergyPlatform/omi) handle this matter! Also this would make the schema not very human readable, because it would be super bloated!

What do you think? Should we handle this in metadata,  [oep](https://github.com/OpenEnergyPlatform/oeplatform) or [omi](https://github.com/OpenEnergyPlatform/omi)? Or should we handle this at all?

**Comment by christian-rli** [comment]
> Hi @christian-rli,
> I cleared all TBDs in schema v1.4.0: [dc9a0be](https://github.com/OpenEnergyPlatform/metadata/commit/dc9a0be001e3d83fce16c26b13ff13daf5c6f3cc)
> Can you have a look, if this still complies with your original intend? Thanks!

Hi @4lm , thank you for all the work first of all and sorry for my tardy response time. I just read through all the descriptions in v1.4.0 and they look fine, just as they are. Nice job :)

I'll have a look into 1.3. now.

**Comment by 4lm** [comment]
@christian-rli and @Bachibouzouk, thanks for all the work on v140 and v130! Are we done now? Can freeze the work on v130 and v140? Can I close this issue?

**Comment by Bachibouzouk** [comment]
I would say yes, we can close it
