### ISSUE TITLE
Add CHANGELOG, CONTRIBUTING and AUTHORS files

### ISSUE THREAD

**Issue by 4lm** [OpenEnergyPlatform/metadata#8]

**Comment by Bachibouzouk** [comment]
You can copy paste them from https://github.com/rl-institut/rli_template

**Comment by 4lm** [comment]
Done. Added CONTRIBUTING.md and CHANGELOG.md. AUTHORS was not provided in template, will leave it out (for now).

**Comment by 4lm** [comment]
Will close the issue.
